In [1]:
import numpy as np
from scipy.linalg import svd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
np.set_printoptions(linewidth=np.inf)  # Extend line width

#### Enter the concordance data

In [2]:
concordance = [[63,66,71,77,79,77,95,95,100],
[61,64,70,79,80,82,89,100,95],
[64,64,70,75,80,79,100,89,95],
[79,75,77,89,95,100,79,82,77],
[80,73,82,91,100,95,80,80,79],
[79,82,80,100,91,89,75,79,77],
[88,77,100,80,82,77,70,70,71],
[86,100,77,82,73,75,64,64,66],
[100,86,88,79,80,79,64,61,63]]

concordance = np.array(concordance)
concordance

array([[ 63,  66,  71,  77,  79,  77,  95,  95, 100],
       [ 61,  64,  70,  79,  80,  82,  89, 100,  95],
       [ 64,  64,  70,  75,  80,  79, 100,  89,  95],
       [ 79,  75,  77,  89,  95, 100,  79,  82,  77],
       [ 80,  73,  82,  91, 100,  95,  80,  80,  79],
       [ 79,  82,  80, 100,  91,  89,  75,  79,  77],
       [ 88,  77, 100,  80,  82,  77,  70,  70,  71],
       [ 86, 100,  77,  82,  73,  75,  64,  64,  66],
       [100,  86,  88,  79,  80,  79,  64,  61,  63]])

#### Center the entries based on column means.

In [4]:
column_means = np.mean(concordance, axis=0)
concordance_centered = concordance - column_means
print(concordance_centered)

[[-14.77777778 -10.33333333  -8.44444444  -6.55555556  -5.44444444  -6.66666667  15.44444444  15.          19.66666667]
 [-16.77777778 -12.33333333  -9.44444444  -4.55555556  -4.44444444  -1.66666667   9.44444444  20.          14.66666667]
 [-13.77777778 -12.33333333  -9.44444444  -8.55555556  -4.44444444  -4.66666667  20.44444444   9.          14.66666667]
 [  1.22222222  -1.33333333  -2.44444444   5.44444444  10.55555556  16.33333333  -0.55555556   2.          -3.33333333]
 [  2.22222222  -3.33333333   2.55555556   7.44444444  15.55555556  11.33333333   0.44444444   0.          -1.33333333]
 [  1.22222222   5.66666667   0.55555556  16.44444444   6.55555556   5.33333333  -4.55555556  -1.          -3.33333333]
 [ 10.22222222   0.66666667  20.55555556  -3.55555556  -2.44444444  -6.66666667  -9.55555556 -10.          -9.33333333]
 [  8.22222222  23.66666667  -2.44444444  -1.55555556 -11.44444444  -8.66666667 -15.55555556 -16.         -14.33333333]
 [ 22.22222222   9.66666667   8.55555556

#### Perform Singular Value Decomposition

In [5]:
# Perform singular value decomposition
U, s, Vt = svd(concordance_centered)

#### Dimensionality reduction - take only the first k eigenvectors and singular values

In [6]:
# Keep the top k singular values and vectors
k = 2            # Choosing 2 dimensions for visualization
U_k = U[:, :k]   # Get all the rows of the first 2 columns
s_k = s[:k]
Vt_k = Vt[:k, :] # Get all the columns of the first 2 rows

#### Visualize U<sub>k</sub>

In [7]:
print(np.array2string(U_k, precision=3, suppress_small=True))

[[-0.433 -0.255]
 [-0.423 -0.113]
 [-0.408 -0.236]
 [ 0.005  0.488]
 [ 0.014  0.516]
 [ 0.096  0.364]
 [ 0.279 -0.155]
 [ 0.396 -0.405]
 [ 0.473 -0.204]]


#### Visualize V<sup>T</sup><sub>k</sub>

In [8]:
print(np.array2string(Vt_k, precision=3, suppress_small=True))

[[ 0.44   0.36   0.25   0.076 -0.004 -0.015 -0.437 -0.452 -0.461]
 [ 0.042 -0.126  0.046  0.471  0.611  0.607 -0.015  0.108 -0.072]]


#### Let's take a look at the singular values and the ∑ matrix.

In [9]:
print(f"This is the s as a 1-dimentional array.\n {s}\n")

Sigma = np.diag(s)
print(f"This is what the actual middle matrix Sigma looks like: \n{np.array2string(Sigma, precision=2, suppress_small=True)}")

This is the s as a 1-dimentional array.
 [8.14632829e+01 3.99533692e+01 2.49032674e+01 1.42329499e+01 1.04158265e+01 6.12695670e+00 4.24402005e+00 2.66757126e+00 4.82315631e-15]

This is what the actual middle matrix Sigma looks like: 
[[81.46  0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.   39.95  0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   24.9   0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.   14.23  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   10.42  0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    6.13  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    4.24  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    2.67  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


#### allclose compares two matrices to see if they are essentially equal (within tolerances). You can see that A_reconstructed is indeed the same as the three matrices multiplied together.

In [ ]:
A_reconstructed = U @ Sigma @ Vt
print (np.allclose(concordance_centered, A_reconstructed))

In [ ]:
A_reconstructed = A_reconstructed + column_means
print(np.array2string(A_reconstructed, precision=2, suppress_small=True))

#### Scale V<sup>T</sup><sub>k</sub> by each singular value s<sub>k</sub>.

In [ ]:
justices_reduced = Vt_k.T * s_k  # This scales each column by the corresponding singular value
justices_reduced

#### Use MinMaxScaler to scale the data to (-1,1)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1, 1))
justices_normalized = scaler.fit_transform(justices_reduced)
justices_normalized

#### 2-D plot of the SVD

In [ ]:
justice_names = ["Alito","Thomas","Gorsuch","Barrett","Kavanaugh","Roberts","Jackson","Kagan","Sotomayor"]
# Take the first two singular values and use them as x- and y-coordinates.
x = justices_normalized[:, 0] # first column
y = justices_normalized[:, 1] # second column

plt.figure(figsize=(8, 6))
plt.scatter(x, y)
for i, name in enumerate(justice_names):
    plt.annotate(name, (x[i], y[i]))

plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
plt.title('Supreme Court Justices: Voting Agreement Patterns')
plt.show()

#### Dimension 3 could reflect seniority/tenure, originalism vs textualism, some other issue.

In [ ]:
k = 3 # Choosing 3 dimensions for visualization
U_k = U[:, :k]
s_k = s[:k]
Vt_k = Vt[:k, :]

# Again, project the justices into the reduced space
justices_reduced = Vt_k.T * s_k
justices_normalized = scaler.fit_transform(justices_reduced)
justices_normalized

In [ ]:
# Create a 3D figure
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Plot the justices in the reduced 3D space, using the first three singular values as coordinates.
ax.scatter(justices_normalized[:, 0], justices_normalized[:, 1], justices_normalized[:, 2])

# Label the axes
ax.set_xlabel('Dimension 1')
ax.set_ylabel('Dimension 2')
ax.set_zlabel('Dimension 3')

# Set the title
ax.set_title('Supreme Court Justices: Voting Concordance in 3D')

# Add labels to the data points
for i, name in enumerate(justice_names):
    x, y, z = justices_normalized[i, :]
    ax.text(x, y, z, name, fontsize=10)
    
# Adjust the aspect ratio and position to make room for z-axis label
ax.set_box_aspect((1, 1, 0.5)) # Increase the depth aspect ratio
ax.set_position([0.1, 0.1, 0.8, 0.8]) # Adjust the position and size of the plot

# Adjust the viewing angle
ax.view_init(elev=30, azim=50)

# Show the plot
plt.show()

In [ ]:
import plotly.graph_objects as go
import pandas as pd
from IPython.display import display, HTML

df = pd.DataFrame({
    'Justice': justice_names,
    'Dimension 1': justices_normalized[:, 0],
    'Dimension 2': justices_normalized[:, 1],
    'Dimension 3': justices_normalized[:, 2]
})

fig = go.Figure(data=[go.Scatter3d(
    x=justices_normalized[:, 0],
    y=justices_normalized[:, 1],
    z=justices_normalized[:, 2],
    mode='markers+text',
    marker=dict(
        size=10,
        color=justices_normalized[:, 0],
        colorscale='Spectral',
        showscale=True,
        colorbar=dict(
            title="Dimension 1",
            x=0.98,
            len=0.8,     # Colorbar takes 80% of height
            y=0.5,       # Centered vertically
            yanchor='middle'
        )
    ),
    text=justice_names,
    textposition="top center",
    textfont=dict(size=12),
    hovertemplate='<b>%{text}</b><br>' +
                  'Dim 1: %{x:.2f}<br>' +
                  'Dim 2: %{y:.2f}<br>' +
                  'Dim 3: %{z:.2f}<br>' +
                  '<extra></extra>'
)])

fig.update_layout(
    width=1400,
    height=1000,
    margin=dict(l=20, r=150, t=0, b=0),
    scene=dict(
        domain=dict(
            x=[0, 0.95],     # Width: leave room for colorbar on right
            y=[0, 0.95]      # Height: match colorbar (centered, 80% height)
        ),
        xaxis=dict(
            range=[-1.5, 1.5],
            title='Dimension 1 (Conservatism)'
        ),
        yaxis=dict(
            range=[-1.5, 1.5],
            title='Dimension 2 (Institutionalism)'
        ),
        zaxis=dict(
            range=[-1.5, 1.5],
            title='Dimension 3'
        ),
        camera=dict(
            eye=dict(x=1.5, y=1.5, z=1.5)
        )
    ),
    title=dict(
        text='Supreme Court Justices: Voting Concordance in 3D',
        y=0.95
    )
)

fig.show()